"""Add shared field to Recipe model

Revision ID: 07351f012619
Revises: 06e76e190521
Create Date: 2023-12-17 14:50:27.306040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07351f012619'
down_revision = '06e76e190521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_recipes')
    op.drop_table('custom_recipe')
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('custom', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_custom_recipe_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('fk_custom_recipe_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('custom')
        batch_op.drop_column('shared')

    op.create_table('custom_recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=False),
    sa.Column('ingredients', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('measure', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_custom_recipe_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=False),
    sa.Column('ingredients', sa.TEXT(), nullable=True),
    sa.Column('measure', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('youtube_link', sa.VARCHAR(length=200), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorite_recipe_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
