"""column measure added

Revision ID: 80778c35d190
Revises: f5725c265e37
Create Date: 2023-06-14 21:41:15.384254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80778c35d190'
down_revision = 'f5725c265e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measure', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('measure')

    # ### end Alembic commands ###
