"""empty message

Revision ID: cc93dc7fb17e
Revises: a780ad267a4c
Create Date: 2023-06-20 21:55:37.000090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc93dc7fb17e'
down_revision = 'a780ad267a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_recipe')
    # ### end Alembic commands ###
