"""measure added to custom_recipe

Revision ID: d9c470966233
Revises: f38f80958655
Create Date: 2023-09-27 10:27:00.290504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c470966233'
down_revision = 'f38f80958655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measure', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.drop_column('measure')

    # ### end Alembic commands ###
