"""empty message

Revision ID: da0405246d74
Revises: 4c2f01952271
Create Date: 2023-06-20 22:51:45.586135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0405246d74'
down_revision = '4c2f01952271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_custom_recipe_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.drop_constraint('fk_custom_recipe_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('instructions')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
