"""shared recipes update

Revision ID: 06e76e190521
Revises: 639f6125caa4
Create Date: 2023-11-10 12:50:54.866386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e76e190521'
down_revision = '639f6125caa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('measure', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('youtube_link', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorite_recipe_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=False),
    sa.Column('ingredients', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('youtube_link', sa.VARCHAR(length=200), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('measure', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorite_recipe_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shared_recipes')
    # ### end Alembic commands ###
