"""recipe table

Revision ID: 15f4c6a20e17
Revises: 668ea73c5587
Create Date: 2023-09-18 16:05:18.586763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f4c6a20e17'
down_revision = '668ea73c5587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('measure', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('youtube_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
