"""custom recipe ingredients format changed

Revision ID: 639f6125caa4
Revises: d9c470966233
Create Date: 2023-10-02 11:18:42.903628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639f6125caa4'
down_revision = 'd9c470966233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
