"""Add image_url field to CustomRecipe

Revision ID: 726ec31667df
Revises: 15f4c6a20e17
Create Date: 2023-09-19 13:44:28.773778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726ec31667df'
down_revision = '15f4c6a20e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_recipe', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
