"""column measure added

Revision ID: a780ad267a4c
Revises: 80778c35d190
Create Date: 2023-06-14 21:53:13.399162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a780ad267a4c'
down_revision = '80778c35d190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measure', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.drop_column('measure')

    # ### end Alembic commands ###
